# ============================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ============================================================

# Nombre de la aplicación (aparece en logs y actuator)
spring.application.name=pc-swaps

# Limite maximo para imagenes subidas por los usuarios.
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Perfil activo: determina qué application.{perfil}.properties se carga
# Cambiar a "prod" para despliegue en producción
spring.profiles.active=dev
